In [1]:
import numpy as np
import pandas as pd



X = np.genfromtxt("hw01_data_points.csv", delimiter = ",", dtype = str)
y = np.genfromtxt("hw01_class_labels.csv", delimiter = ",", dtype = int)

In [2]:
# STEP 3
# first 50000 data points should be included to train
# remaining 44727 data points should be included to test
# should return X_train, y_train, X_test, and y_test
def train_test_split(X, y):
    # your implementation starts below
    X_train= X[:50000, :]
    y_train= y[:50000]
    X_test= X[50000:]
    y_test= y[50000:]
    
    # your implementation ends above
    return(X_train, y_train, X_test, y_test)

X_train, y_train, X_test, y_test = train_test_split(X, y)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)


(50000, 21)
(50000,)
(44727, 21)
(44727,)


In [3]:
# STEP 4
# assuming that there are K classes
# should return a numpy array with shape (K,)
def estimate_prior_probabilities(y):
    # your implementation starts below
    ones = np.where(y==1,1,0)
    twos = np.where(y==2,1,0)
    ones_prob = sum(ones)/y.shape[0]
    twos_prob= sum(twos)/y.shape[0]
    class_priors = np.array([ones_prob, twos_prob])
    
    # your implementation ends above
    return(class_priors)

class_priors = estimate_prior_probabilities(y_train)
print(class_priors)

[0.04466 0.95534]


In [6]:
# STEP 5
# assuming that there are K classes and D features
# should return four numpy arrays with shape (K, D)
def estimate_nucleotide_probabilities(X, y):
    # your implementation starts below
    
    pAcd1 = np.array([])
    pAcd2 = np.array([])
    pCcd1 = np.array([])
    pCcd2 = np.array([])    
    pGcd1 = np.array([])
    pGcd2 = np.array([])
    pTcd1 = np.array([])
    pTcd2 = np.array([])
    for i in range(X.shape[1]):
        A_1 = np.where(X[:, i] =="A",1,0) * np.where(y == 1, 1, 0 )
        A_2 = np.where(X[:, i] =="A",1,0) * np.where(y == 2, 1, 0 )
        pAcd1 = np.append(pAcd1, sum(A_1)/ sum(np.where(y == 1, 1, 0 )))
        pAcd2 = np.append(pAcd2, sum(A_2)/ sum(np.where(y == 2, 1, 0 )))
        pAcd= np.array([pAcd1,pAcd2])
        
        C_1 = np.where(X[:, i] =="C",1,0) * np.where(y == 1, 1, 0 )
        C_2 = np.where(X[:, i] =="C",1,0) * np.where(y == 2, 1, 0 )
        pCcd1 = np.append(pCcd1, sum(C_1)/ sum(np.where(y == 1, 1, 0 )))
        pCcd2 = np.append(pCcd2, sum(C_2)/ sum(np.where(y == 2, 1, 0 )))
        pCcd= np.array([pCcd1,pCcd2])
        
        G_1 = np.where(X[:, i] =="G",1,0) * np.where(y == 1, 1, 0 )
        G_2 = np.where(X[:, i] =="G",1,0) * np.where(y == 2, 1, 0 )
        pGcd1 = np.append(pGcd1, sum(G_1)/ sum(np.where(y == 1, 1, 0 )))
        pGcd2 = np.append(pGcd2, sum(G_2)/ sum(np.where(y == 2, 1, 0 )))
        pGcd= np.array([pGcd1,pGcd2])
        
        T_1 = np.where(X_train[:, i] =="T",1,0) * np.where(y == 1, 1, 0 )
        T_2 = np.where(X_train[:, i] =="T",1,0) * np.where(y == 2, 1, 0 )
        pTcd1 = np.append(pTcd1, sum(T_1)/ sum(np.where(y == 1, 1, 0 )))
        pTcd2 = np.append(pTcd2, sum(T_2)/ sum(np.where(y == 2, 1, 0 )))
        pTcd= np.array([pTcd1,pTcd2])
  
    
    # your implementation ends above
    return(pAcd, pCcd, pGcd, pTcd)

pAcd, pCcd, pGcd, pTcd = estimate_nucleotide_probabilities(X_train, y_train)
print(pAcd)
print(pCcd)
print(pGcd)
print(pTcd)


[[0.18674429 0.17913121 0.1437528  0.13390058 0.11912226 0.11374832
  0.10523959 0.10076131 0.08687864 0.07613077 0.06941335 0.08687864
  0.10120914 0.09628303 0.08105687 0.07926556 0.23510972 0.05015674
  0.24540976 0.23734886 0.2539185 ]
 [0.26832332 0.27719974 0.2723219  0.25808613 0.28153328 0.27784872
  0.27219629 0.26087048 0.25488308 0.26618795 0.27385015 0.26955848
  0.28913266 0.28486193 0.27694852 0.25260117 0.27766031 0.24981682
  0.28335462 0.28025624 0.29279628]]
[[0.28616211 0.28526646 0.28571429 0.29422302 0.31168831 0.31751008
  0.31034483 0.31258397 0.29735781 0.28034035 0.30541872 0.31840573
  0.33811017 0.36945813 0.38916256 0.33990148 0.2955665  0.67845947
  0.14464845 0.21988356 0.2539185 ]
 [0.22821195 0.22961459 0.22318756 0.22536479 0.21688613 0.22747922
  0.22278979 0.22431804 0.24516926 0.22618125 0.20903553 0.21158959
  0.20369711 0.20145707 0.22607658 0.24527393 0.21198736 0.32248205
  0.22067536 0.24414345 0.210815  ]]
[[0.15718764 0.15002239 0.1518137  0.1

In [11]:
# STEP 6
# assuming that there are N data points and K classes
# should return a numpy array with shape (N, K)
def calculate_score_values(X, pAcd, pCcd, pGcd, pTcd, class_priors):
    # your implementation starts below
    arr = np.ones((X.shape[0],2))
    
    for k in range(X.shape[0]):
        for i in range(X.shape[1]):
            if X[k,i]=="A":
                arr[k,0] *= pAcd[0,i]

            if X[k,i]=="C":
                arr[k,0] *= pCcd[0,i] 

            if X[k,i]=="G":
                arr[k,0] *= pGcd[0,i]

            if X[k,i]=="T":
                arr[k,0] *= pTcd[0,i]

            if X[k,i]=="A":
                arr[k,1] *= pAcd[1,i]

            if X[k,i]=="C":
                arr[k,1] *= pCcd[1,i] 

            if X[k,i]=="G":
                arr[k,1] *= pGcd[1,i]

            if X[k,i]=="T":
                arr[k,1] *= pTcd[1,i]

    g_class1 = np.log(arr[:,0]) + np.log(class_priors[0])
    g_class2 = np.log(arr[:,1]) + np.log(class_priors[1])
    score_values = np.column_stack((g_class1, g_class2))
    
    # your implementation ends above
    return(score_values)

scores_train = calculate_score_values(X_train, pAcd, pCcd, pGcd, pTcd, class_priors)
print(scores_train)

scores_test = calculate_score_values(X_test, pAcd, pCcd, pGcd, pTcd, class_priors)
print(scores_test)


[[-32.29602984 -28.67631805]
 [-35.36510932 -29.06687849]
 [-33.1594779  -28.50829296]
 ...
 [-37.17901126 -29.28659414]
 [-35.6365549  -29.75138901]
 [-28.72885394 -28.68471489]]
[[-31.88852108 -28.73182527]
 [-40.83809258 -29.40573888]
 [-30.6177392  -29.98270774]
 ...
 [-38.49757139 -28.9923932 ]
 [-24.40343148 -29.115305  ]
 [-37.58089652 -28.27846954]]


In [10]:
# STEP 7
# assuming that there are K classes
# should return a numpy array with shape (K, K)
def calculate_confusion_matrix(y_truth, scores):
    # your implementation starts below
    pred = np.ones(scores.shape[0], dtype=int)

    for i in range(scores.shape[0]):
        if scores[i,0] < scores[i,1]:
            pred[i] = 2
        else:
            continue
    confusion_matrix = pd.crosstab(pred.T, y_truth.T, 
                                   rownames = ["pred"], 
                                   colnames = ["y_truth"])
    
    confusion_matrix = confusion_matrix.to_numpy()
    # your implementation ends above
    return(confusion_matrix)

confusion_train = calculate_confusion_matrix(y_train, scores_train)
print(confusion_train)

confusion_test = calculate_confusion_matrix(y_test, scores_test)
print(confusion_test)

[[ 1489  1460]
 [  744 46307]]
[[ 1314  1300]
 [  686 41427]]
